name: sameboy
base: core18
adopt-info: sameboy
summary: SameBoy - A Friendly and Powerful Game Boy Emulator
description: |
    SameBoy is a user friendly Game Boy, Game Boy Color and Super Game Boy emulator
    for macOS, Windows and Unix-like platforms.
    
    SameBoy is extremely accurate and includes a wide range of powerful debugging features,
    making it ideal for both casual players and developers.
    
    In addition to accuracy and developer capabilities, SameBoy has all the features
    one would expect from an emulator – from save states to scaling filters.
confinement: strict
grade: stable

plugs:
  gtk-3-themes:
    default-provider: gtk-common-themes:gtk-3-themes
    interface: content
    target: $SNAP/data-dir/themes
  sound-themes:
    default-provider: gtk-common-themes:sound-themes
    interface: content
    target: $SNAP/data-dir/sounds
  gnome-3-28-1804:
    default-provider: gnome-3-28-1804:gnome-3-28-1804
    interface: content
    target: $SNAP/gnome-platform
  icon-themes:
    default-provider: gtk-common-themes:icon-themes
    interface: content
    target: $SNAP/data-dir/icons

apps:
  sameboy:
    command: desktop-launch $SNAP/usr/bin/sameboy
    plugs:
      - x11
      - wayland
      - unity7
      - opengl
      - joystick
      - audio-playback
      - home

parts:
  rgbds:
    source: https://github.com/rednex/rgbds.git
    plugin: make
    override-build: |
      snapcraftctl build
      make install
    build-packages:
     - g++
     - make
     - byacc

  sameboy:
    after: [rgbds, desktop-gtk, gtk-locales]
    plugin: nil
    source: https://github.com/liji32/sameboy.git
    override-build: |
      last_committed_tag="$(git describe --abbrev=0 --tags)"
      trimmed_tag="$(echo $last_committed_tag | sed 's/desc\///' | sed 's/git//' | sed 's/^v//')"
      last_released_tag="$(snap info sameboy | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${trimmed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
        snapcraftctl set-version $(git -C ../src describe --abbrev=0 --tags | sed 's/desc\///' | sed 's/git//' | sed 's/^v//')
      else
        snapcraftctl set-version $(git -C ../src describe | sed 's/desc\///')
      fi    
      snapcraftctl build
      CONF=release make
      strip build/bin/SDL/sameboy
      cp -r build/bin/SDL/* $SNAPCRAFT_PART_INSTALL/usr/bin/
      
    build-packages:
      - clang
      - llvm-dev
      - libpng-dev
      - libsdl2-dev
      - libunity-dev
    stage-packages:
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libglu1-mesa
      - libwayland-egl1-mesa
      - libpng16-16
      - libsdl2-2.0-0
      - libstdc++6
      - libunity9
      - locales-all

  desktop-gtk:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    build-packages:
      - build-essential

    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - locales-all
      - xdg-user-dirs
      - libcanberra-gtk3-module
      - libgdk-pixbuf2.0-0

  gtk-locales:
    plugin: nil
    build-packages:
      - apt
      - dpkg
    override-pull: |
      set -eux
      apt download "language-pack-gnome-*-base"
    override-build: |
      set -eux
      for deb in *.deb; do dpkg-deb -x $deb .; done
      find usr/share/locale-langpack -type f -not -name "gtk20*.mo" -and -not -name "gtk30*.mo" -exec rm '{}' \;
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share
      cp -R usr/share/locale-langpack $SNAPCRAFT_PART_INSTALL/usr/share/

