name: sameboy
base: core18
license: MIT
adopt-info: sameboy
summary: SameBoy - A Friendly and Powerful Game Boy Emulator
description: |
    Lior Halphon's SameBoy is a user friendly Game Boy, Game Boy Color and
    Super Game Boy emulator for macOS, Windows and Unix-like platforms.
    
    SameBoy is extremely accurate and includes a wide range of powerful debugging features,
    making it ideal for both casual players and developers.
    
    In addition to accuracy and developer capabilities, SameBoy has all the features
    one would expect from an emulator – from save states to scaling filters.
confinement: strict
grade: stable

apps:
  sameboy:
    command: desktop-launch $SNAP/usr/bin/sameboy
    extensions: [gnome-3-28]
    plugs:
      - x11
      - wayland
      - unity7
      - opengl
      - joystick
      - audio-playback
      - home
      - removable-media

    environment:
      DBUS_FATAL_WARNINGS: 0

parts:
  rgbds:
    source: https://github.com/rednex/rgbds.git
    plugin: make
    override-build: |
      snapcraftctl build
      make install
    build-packages:
     - g++
     - make
     - bison
     - byacc

  sameboy:
    after: [rgbds, gtk-locales]
    plugin: nil
    source: https://github.com/liji32/sameboy.git
    override-build: |
      last_committed_tag="$(git describe --abbrev=0 --tags)"
      trimmed_tag="$(echo $last_committed_tag | sed 's/desc\///' | sed 's/git//' | sed 's/^v//')"
      last_released_tag="$(snap info sameboy | awk '$1 == "latest/beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${trimmed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
        snapcraftctl set-version $(git describe --abbrev=0 --tags | sed 's/desc\///' | sed 's/git//' | sed 's/^v//')
      else
        snapcraftctl set-version "$(git describe --always)"
      fi    
      snapcraftctl build
      CONF=release make
      strip --strip-all build/bin/SDL/sameboy
      cp -r build/bin/SDL/* $SNAPCRAFT_PART_INSTALL/usr/bin/
      
    build-packages:
      - clang
      - llvm-dev
      - libpng-dev
      - libsdl2-dev
      - libunity-dev
    stage-packages:
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libglu1-mesa
      - libwayland-egl1-mesa
      - libpng16-16
      - libsdl2-2.0-0
      - libstdc++6
      - libunity9

  gtk-locales:
    plugin: nil
    build-packages:
      - apt
      - dpkg
    override-pull: |
      set -eux
      apt download "language-pack-gnome-*-base"
    override-build: |
      set -eux
      for deb in *.deb; do dpkg-deb -x $deb .; done
      find usr/share/locale-langpack -type f -not -name "gtk20*.mo" -and -not -name "gtk30*.mo" -exec rm '{}' \;
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share
      cp -R usr/share/locale-langpack $SNAPCRAFT_PART_INSTALL/usr/share/

